/* ============================================================
   Memofun — Textos de la Presentación del proyecto (ES)
   Language-specific file. Loaded conditionally from index.html
   based on App.i18n.locale().
   ============================================================ */
(function () {
  'use strict';

  App.i18n.register({
    "pageTitle": 'Presentación del proyecto',
    "routeNotice": 'Esta página no se enlaza desde la aplicación. Solo se llega escribiendo la dirección.',
    "tagline": 'Una aplicación para la autonomía.',
    "lead1": 'Memofun es una ',
    "leadStrong": 'aplicación web de tarjetas de memoria',
    "lead2": ' pensada para que las personas con discapacidad intelectual repasen por sí mismas vocabulario y conceptos del colegio, sin presión y con respeto a su privacidad.',
    "navOrigin": 'El origen',
    "navPrinciples": 'Los principios',
    "navTech": 'Cómo está hecha',
    "navAreas": 'Las áreas de trabajo',
    "navSiblings": 'Proyectos hermanos',
    "navAuthorship": 'Quiénes la hacen',
    "navCollaborate": 'Cómo ayudar',
    "originTitle": 'El origen',
    "originP1a": 'Memofun nace de una pregunta que se repite al final de cada sesión de apoyo educativo: ',
    "originP1em": '¿qué pasa entre una sesión y la siguiente?',
    "originP2": 'La persona con discapacidad intelectual practica con su profesora o su terapeuta en consulta, pero después está sola en casa, en el colegio o en su tiempo libre. Queríamos una herramienta que respetase esa autonomía, que diese seguridad a las familias y que sirviese a la profesional como complemento entre sesiones, no como sustituto.',
    "originP3": 'Esta aplicación es el resultado: cerca de 190 barajas de tarjetas, todas en Lectura Fácil, todas accesibles, todas pensadas para que la persona usuaria pueda usarlas a su propio ritmo.',
    "principlesTitle": 'Los principios que no negociamos',
    "principlesIntro": 'Estas ideas están escritas primero en el código y después en los textos. Si una decisión las rompe, esa decisión está mal.',
    "principleAutonomyTitle": '🤲 Autonomía real',
    "principleAutonomyText": 'La persona usuaria puede usar la aplicación sin un profesional al lado. Si necesita ayuda constante, algo no está bien resuelto.',
    "principleNoPressureTitle": '🚫 Sin presión',
    "principleNoPressureText": 'Nada de cronómetros, ni "game over", ni puntuaciones negativas. El error se responde con ánimo y se puede reintentar sin límite.',
    "principlePrivacyTitle": '🔒 Privacidad por defecto',
    "principlePrivacyText": 'Sin registro, sin cookies, sin analítica, sin cuentas. Todo el progreso se guarda únicamente en el dispositivo de la persona.',
    "principleEasyReadTitle": '📖 Lectura Fácil',
    "principleEasyReadText": 'Frases cortas, una idea por frase, vocabulario cotidiano. Cero tecnicismos en la interfaz que ve la persona usuaria.',
    "principleAccessibilityTitle": '♿ Accesibilidad universal',
    "principleAccessibilityText": 'Botones grandes, alto contraste, audio solo cuando la gamificación o el diseño de la actividad lo requiera (p. ej. escuchar la pregunta en voz alta), navegación completa por teclado, y respeto al modo de pocas animaciones del sistema.',
    "principleSoberTechTitle": '🧱 Tecnología sobria',
    "principleSoberTechText": 'HTML, CSS y JavaScript sin frameworks. Funciona sin internet y se puede instalar como aplicación. Código abierto, en un repositorio público.',
    "techTitle": 'Cómo está hecha',
    "techIntro1": 'Memofun es una aplicación web instalable (PWA) compuesta por más de ',
    "techIntroStrong": '20 páginas HTML estáticas',
    "techIntro2": ': una landing, una herramienta de estudio, cerca de 190 barajas de tarjetas y rutas ocultas para familias, profesionales y mantenimiento.',
    "techItem1Label": 'Sin servidor propio',
    "techItem1Text": 'es un conjunto de archivos servidos por un hosting estático. No hay backend, ni bases de datos, ni API propia.',
    "techItem2Label": 'Funciona sin conexión',
    "techItem2Text": 'una vez instalada, abre aunque no haya internet gracias al service worker y al caché local. Las barajas ya abiertas quedan disponibles offline.',
    "techItem3Label": 'Persistencia solo en',
    "techItem3Text": 'el progreso (estrellas y barajas terminadas) vive en el navegador del dispositivo. Nunca se envía a ningún sitio.',
    "techItem4Label": 'Sin frameworks ni build step',
    "techItem4Text1": 'JavaScript clásico compatible con navegadores antiguos y con el protocolo',
    "techItem4Text2": '. Pensado para que un técnico novel pueda leer y modificar una baraja sin sorpresas.',
    "techItem5Label": 'Código abierto (licencia MIT)',
    "techItem5Text": 'cualquiera puede leerlo, auditarlo y proponer mejoras. Las decisiones de producto están escritas en este repositorio, no en presentaciones cerradas.',
    "techItem6Label": 'Internacionalización desde el inicio',
    "techItem6Text": 'cada texto vive en un archivo por idioma. Hoy Memofun está disponible en español de España e inglés.',
    "techItem7Label": 'Dependencias externas: ninguna',
    "techItem7Text": ', excepto la descarga de las fuentes tipográficas Atkinson Hyperlegible y Nunito (usadas por su alta legibilidad).',
    "areasTitle": 'Las áreas de trabajo',
    "areasIntro1": 'Las cerca de 190 barajas se agrupan en ',
    "areasIntroStrong": 'seis bloques temáticos',
    "areasIntro2": ', cada uno con su color identificativo. Una misma materia puede aparecer en varias etapas (por ejemplo, Lengua Castellana se trabaja desde Primaria hasta ESO), pero cada baraja aparece una sola vez en el menú, en su etapa.',
    "areaPrimaryTitle": '📚 Primaria',
    "areaPrimaryText": 'Ciencias naturales, ciencias sociales, lengua castellana y literatura de 1º a 6º.',
    "areaPrimaryCount": '~85 barajas',
    "areaEsoTitle": '🎒 ESO',
    "areaEsoText": 'Biología y geología, geografía e historia, lengua castellana y literatura de 1º a 4º.',
    "areaEsoCount": '~70 barajas',
    "areaFpTitle": '🛠️ Formación Profesional',
    "areaFpText": 'Ciclos formativos de gestión administrativa y atención al cliente, básico y medio.',
    "areaFpCount": '~30 barajas',
    "areaConceptsTitle": '💡 Conceptos generales',
    "areaConceptsText": 'Tarjetas de vocabulario transversal, útiles en distintas etapas.',
    "areaConceptsCount": '1 baraja',
    "areaGeoTitle": '🌍 Mapa del mundo',
    "areaGeoText": 'Banderas, capitales, ciudades, continentes, geografía física y récords del mundo.',
    "areaGeoCount": '~10 barajas',
    "areaSelfTitle": '🌱 A tu ritmo',
    "areaSelfText": 'Modo libre sin baraja predefinida: la persona crea sus propias tarjetas.',
    "areaSelfCount": 'Modo libre',
    "areasNote1": 'Total: ',
    "areasNoteStrong": '~190 barajas',
    "areasNote2": ', organizadas para que la persona elija por interés, no por obligación. El orden del menú no es un itinerario: cada persona hace su propio camino.',
    "siblingsTitle": 'Proyectos hermanos',
    "siblingsIntro": 'Memofun es uno más de un pequeño grupo de proyectos hermanos: mismo equipo, misma filosofía de accesibilidad y sin servidor propio. Cada uno es un servicio independiente, con su propio dominio, al que se puede llegar desde aquí.',
    "siblingRoutimeName": 'Routime',
    "siblingRoutimeText": 'Rutinas y autonomía del día a día.',
    "siblingCalculiaName": 'Calculia',
    "siblingCalculiaText": 'Cálculo y razonamiento lógico.',
    "siblingOkeymoneyName": 'Okeymoney',
    "siblingOkeymoneyText": 'Finanzas personales y autonomía cotidiana.',
    "siblingSinonimiaName": 'Sinonimia',
    "siblingSinonimiaText": 'Diccionario en lectura fácil.',
    "siblingTeclatlonName": 'Teclatlon',
    "siblingTeclatlonText": 'Mecanografía con el teclado físico.',
    "siblingLinkHint": 'Se abre en una pestaña nueva.',
    "authorshipTitle": 'Quiénes la hacen',
    "authorshipP1a": 'Memofun es una iniciativa de ',
    "authorshipP1b": ', un estudio independiente que trabaja en proyectos abiertos con impacto social y educativo.',
    "authorshipP2": 'La aplicación se construye con la participación de personas con discapacidad intelectual, familias, profesionales de apoyo y profesorado, que prueban cada cambio y revisan el contenido antes de que llegue a producción.',
    "authorshipP3": 'El código, el texto y las decisiones se publican en abierto para que cualquier persona o equipo pueda auditarlos, aprender de ellos y adaptarlos a otros contextos.',
    "collaborateTitle": 'Cómo ayudar',
    "collaborateIntro": 'Memofun es un proyecto abierto. Hay formas de colaborar que no requieren programar:',
    "collaborateItem1Label": 'Probar y compartir feedback',
    "collaborateItem1Text": 'las familias, profesionales y personas usuarias que prueban la aplicación y cuentan qué funciona y qué no, son la pieza clave del proyecto. Los errores de Lectura Fácil, los tonos poco amables y las tarjetas que cuestan entender se detectan usándolas.',
    "collaborateItem2Label": 'Proponer barajas',
    "collaborateItem2Text": 'si una materia o un tema no tiene barajas, o las que hay se pueden mejorar, se puede proponer una baraja nueva. La revisión de contenido la valida una profesional antes de pasar a código.',
    "collaborateItem3Label": 'Revisar contenido',
    "collaborateItem3Text": 'traducciones, ejemplos culturalmente adecuados, explicaciones accesibles. La interfaz que ve la persona usuaria es en Lectura Fácil y se beneficia especialmente de ojos ajenos.',
    "collaborateItem4Label": 'Contribuir código',
    "collaborateItem4Text": 'el repositorio es público. Cambios pequeños (un icono, una traducción, una corrección de estilo) y grandes (barajas nuevas, accesibilidad, soporte para más idiomas) se aceptan siempre que respeten los principios del proyecto.',
    "collaborateItem5Label": 'Difundir',
    "collaborateItem5Text": 'contar que existe. Muchas familias, profesionales y centros no saben que hay herramientas como esta hasta que alguien se la enseña.',
    "collaborateOutro1": 'Toda la documentación necesaria para empezar está en los archivos',
    "collaborateOutro3": 'y',
    "collaborateOutro4": 'del repositorio.',
    "footerActivities": 'Ir a las barajas'
  }, 'es');
})();
