/* Memofun — scripts/config-parser.js
 *
 * Parses a content config (frontmatter + optional "# Índice" section) —
 * the project's content ingestion format (see doc/es/tecnico.md §8 and
 * doc/es/guia-interna-crear-barajas.md). Pure parsing, zero dependencies, no
 * network, no API key: content itself is no longer generated by calling
 * an external AI API from a script — it's written directly by the AI
 * coding agent working in this repository (see CLAUDE.md "Generating
 * deck content"). This module only understands the *shape* of a config
 * file; scripts/check.js uses it to validate every file under
 * doc/curriculum/.
 */

'use strict';

/** Minimal frontmatter parser: one `key: value` per line, quotes optional. */
function parseFrontmatter(raw) {
  const cfg = {};
  raw.split('\n').forEach((line) => {
    const m = line.match(/^([a-zA-Z_]+):\s*(.*)$/);
    if (!m) return;
    let value = m[2].trim();
    if (/^".*"$/.test(value) || /^'.*'$/.test(value)) value = value.slice(1, -1);
    else if (/^\d+$/.test(value)) value = parseInt(value, 10);
    cfg[m[1]] = value;
  });
  return cfg;
}

function slugify(text) {
  return (
    text
      .toLowerCase()
      .normalize('NFD')
      .replace(/[̀-ͯ]/g, '')
      .replace(/[^a-z0-9]+/g, '_')
      .replace(/^_+|_+$/g, '') || 'memofun'
  );
}

/**
 * Pulls an optional "# Índice" (or "# Indice") section out of the
 * Markdown body: a bullet list of subtopics the deck must cover, one by
 * one, instead of being freely improvised. Either a bare `tema` (pick
 * your own subtopics) or a `tema` + `Índice` (follow this outline). The
 * matched heading+list block is removed from the returned context so it
 * isn't duplicated in free-text notes.
 */
function parseIndice(body) {
  // The lookahead avoids a bare `$`: with the /m flag `$` matches at every
  // line ending, which would make the lazy `[\s\S]*?` stop after the
  // índice's first bullet line instead of consuming the whole list.
  // `(?![\s\S])` only matches true end-of-string, immune to /m.
  const match = body.match(/^(#{1,6})[ \t]*(?:[íÍ]ndice|indice)[ \t]*\r?\n([\s\S]*?)(?=\r?\n#{1,6}[ \t]|(?![\s\S]))/im);
  if (!match) {
    return { indice: [], contexto: body.trim() };
  }
  const indice = match[2]
    .split('\n')
    .map((line) => line.match(/^\s*[-*][ \t]+(.+?)\s*$/))
    .filter(Boolean)
    .map((m) => m[1].trim())
    .filter(Boolean);
  const contexto = (body.slice(0, match.index) + body.slice(match.index + match[0].length)).trim();
  return { indice, contexto };
}

function parseMarkdown(text) {
  const match = text.match(/^---\s*\n([\s\S]*?)\n---\s*\n?([\s\S]*)$/);
  if (!match) {
    throw new Error("El archivo no tiene el formato esperado (frontmatter YAML entre '---').");
  }
  const cfg = parseFrontmatter(match[1]);
  if (!cfg.tema) {
    throw new Error("El frontmatter debe incluir el campo 'tema'.");
  }
  cfg.tema = String(cfg.tema).trim();
  cfg.nivel = cfg.nivel || 'intermedio';
  cfg.cantidad = cfg.cantidad || 10;
  cfg.idioma = cfg.idioma || 'es';
  cfg.salida = cfg.salida || `${slugify(cfg.tema)}.json`;
  const { indice, contexto } = parseIndice(match[2]);
  cfg.indice = indice;
  cfg.contexto = contexto;
  return cfg;
}

module.exports = { parseFrontmatter, slugify, parseIndice, parseMarkdown };
